features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://inno-news-thumbnail(1).png'
favicon:
  use_default: false
  path: 'public://inno-news-thumbnail.png'
  mimetype: image/png
