label: दस्तावेज
description: 'फ़ाइलों को ढूंढें और प्रबंधित करें।'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: फिल्टर
          reset_button_label: 'दोबारा से स्थापित करें|'
          exposed_sorts_label: 'क्रमबद्ध द्वारा'
          sort_asc_label: Asc
          sort_desc_label: अवरोही
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
          expose:
            items_per_page_label: 'विषय प्रति पृष्ठ'
            items_per_page_options_all_label: '-सभी-'
            offset_label: Offset
      fields:
        fid:
          label: 'ऍफ़ आई डी'
        filename:
          label: नाम
          separator: ', '
        filemime:
          label: 'माइम प्रकार'
        filesize:
          label: आकार
        status:
          label: अवस्था
          settings:
            format_custom_false: अस्थाई
            format_custom_true: स्थाई
        created:
          label: 'अपलोड की तारीख'
      filters:
        filename:
          expose:
            label: 'फ़ाइल का नाम'
        filemime:
          expose:
            label: 'माइम प्रकार'
        status:
          expose:
            label: अवस्था
      title: दस्तावेज
      empty:
        area_text_custom:
          content: 'कोई फाइल उपलब्ध नहीं  है'
  page_1:
    display_title: 'फ़ाइलें अवलोकन'
    display_options:
      menu:
        title: दस्तावेज
  page_2:
    display_options:
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
          expose:
            items_per_page_label: 'विषय प्रति पृष्ठ'
            items_per_page_options_all_label: '-सभी-'
            offset_label: Offset
      fields:
        entity_label:
          label: इकाई
        type:
          label: 'इकाई का प्रकार'
        module:
          label: 'पंजीकृत मॉड्यूल'
        count:
          label: 'प्रियोग संख्या'
      arguments:
        fid:
          exception:
            title: सभी
          title: '{{ arguments.fid }} के लिए फ़ाइल उपयोग जानकारी'
