label: 'ताजा खबर'
description: 'समाचार प्रकार की नवीनतम निर्मित सामग्री दिखाता है।'
display:
  default:
    display_title: मास्टर्
    display_options:
      exposed_form:
        options:
          submit_button: लागू
          reset_button_label: रीसेट
          exposed_sorts_label: 'इसके अनुसार क्रमबद्ध करें'
          sort_asc_label: आरोही
          sort_desc_label: उतरते
      pager:
        options:
          expose:
            items_per_page_label: 'आइटम प्रति पेज'
            offset_label: ओफ़्सेट
      filters:
        tid:
          expose:
            label: 'श्रेणी चुनना'
            description: 'समाचार सामग्री प्रकार की श्रेणियाँ'
          group_info:
            label: 'टैक्सोनॉमी टर्म है'
      title: 'ताजा खबर'
  block_1:
    display_title: खंड
  page_1:
    display_title: पृष्ठ
