label: 'नए सदस्य'
description: 'साइट पर नवीनतम उपयोगकर्ता खातों की एक सूची दिखाता है।'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: 'लागू करें'
          reset_button_label: 'दोबारा से स्थापित करें|'
          exposed_sorts_label: 'क्रमबद्ध द्वारा'
          sort_desc_label: अवरोही
          sort_asc_label: आरोही
      title: 'नए सदस्य'
    display_title: मास्टर्
  block_1:
    display_title: 'नए सदस्य'
    display_options:
      display_description: 'नये उपयोगकर्ताओं की सूची'
      block_description: 'नए सदस्य'
      block_category: प्रयोक्ता
