label: 'समाचार प्रदर्शन'
description: 'समाचार प्रदर्शन मोड में समाचार प्रदर्शित करना।'
display:
  default:
    display_title: मास्टर्
    display_options:
      exposed_form:
        options:
          submit_button: लागू
          reset_button_label: रीसेट
          exposed_sorts_label: 'इसके अनुसार क्रमबद्ध करें'
          sort_asc_label: आरोही
          sort_desc_label: उतरते
      title: 'समाचार प्रदर्शन'
  page_1:
    display_title: पृष्ठ
